# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/connectivity_transaction_layer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/connectivity_transaction_layer.proto',
  package='ctl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n(ctl/connectivity_transaction_layer.proto\x12\x03\x63tl\"\x88\x01\n\x17\x43onnectivityTransaction\x12\x12\n\noriginator\x18\x01 \x01(\x06\x12\x13\n\x0bsequence_id\x18\x02 \x01(\x04\x12\x1b\n\x06\x61\x63tion\x18\x03 \x01(\x0e\x32\x0b.ctl.Action\x12\x16\n\x0epayload_format\x18\x04 \x01(\r\x12\x0f\n\x07payload\x18\x05 \x01(\x0c*\x84\x01\n\x06\x41\x63tion\x12\x16\n\x12\x41\x43TION_UNSPECIFIED\x10\x00\x12\x11\n\rACTION_INFORM\x10\x01\x12\x0e\n\nACTION_GET\x10\x02\x12\x0e\n\nACTION_SET\x10\x03\x12\x16\n\x12\x41\x43TION_RESPOND_ACK\x10\x04\x12\x17\n\x13\x41\x43TION_RESPOND_NACK\x10\x05\x62\x06proto3')
)

_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='ctl.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACTION_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_INFORM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_GET', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_SET', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_RESPOND_ACK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTION_RESPOND_NACK', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=189,
  serialized_end=321,
)
_sym_db.RegisterEnumDescriptor(_ACTION)

Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
ACTION_UNSPECIFIED = 0
ACTION_INFORM = 1
ACTION_GET = 2
ACTION_SET = 3
ACTION_RESPOND_ACK = 4
ACTION_RESPOND_NACK = 5



_CONNECTIVITYTRANSACTION = _descriptor.Descriptor(
  name='ConnectivityTransaction',
  full_name='ctl.ConnectivityTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='originator', full_name='ctl.ConnectivityTransaction.originator', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='ctl.ConnectivityTransaction.sequence_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='ctl.ConnectivityTransaction.action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_format', full_name='ctl.ConnectivityTransaction.payload_format', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ctl.ConnectivityTransaction.payload', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=186,
)

_CONNECTIVITYTRANSACTION.fields_by_name['action'].enum_type = _ACTION
DESCRIPTOR.message_types_by_name['ConnectivityTransaction'] = _CONNECTIVITYTRANSACTION
DESCRIPTOR.enum_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectivityTransaction = _reflection.GeneratedProtocolMessageType('ConnectivityTransaction', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIVITYTRANSACTION,
  '__module__' : 'ctl.connectivity_transaction_layer_pb2'
  # @@protoc_insertion_point(class_scope:ctl.ConnectivityTransaction)
  })
_sym_db.RegisterMessage(ConnectivityTransaction)


# @@protoc_insertion_point(module_scope)
