# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/device_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl import version_pb2 as ctl_dot_version__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/device_id.proto',
  package='ctl',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63tl/device_id.proto\x12\x03\x63tl\x1a\x11\x63tl/version.proto\"i\n\x08\x44\x65viceId\x12\x19\n\x11protocol_revision\x18\x01 \x01(\r\x12\x1c\n\x14\x64\x65vice_serial_number\x18\x02 \x01(\x0c\x12$\n\x0esystem_version\x18\x03 \x01(\x0b\x32\x0c.ctl.Versionb\x06proto3')
  ,
  dependencies=[ctl_dot_version__pb2.DESCRIPTOR,])




_DEVICEID = _descriptor.Descriptor(
  name='DeviceId',
  full_name='ctl.DeviceId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol_revision', full_name='ctl.DeviceId.protocol_revision', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_serial_number', full_name='ctl.DeviceId.device_serial_number', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system_version', full_name='ctl.DeviceId.system_version', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=152,
)

_DEVICEID.fields_by_name['system_version'].message_type = ctl_dot_version__pb2._VERSION
DESCRIPTOR.message_types_by_name['DeviceId'] = _DEVICEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceId = _reflection.GeneratedProtocolMessageType('DeviceId', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEID,
  '__module__' : 'ctl.device_id_pb2'
  # @@protoc_insertion_point(class_scope:ctl.DeviceId)
  })
_sym_db.RegisterMessage(DeviceId)


# @@protoc_insertion_point(module_scope)
