# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/AppX1Command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import AppX1Gatt_pb2 as ctl_dot_iox_dot_AppX1Gatt__pb2
from ctl.iox import X1Datalog_pb2 as ctl_dot_iox_dot_X1Datalog__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/AppX1Command.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63tl/iox/AppX1Command.proto\x12\x07\x63tl.iox\x1a\x17\x63tl/iox/AppX1Gatt.proto\x1a\x17\x63tl/iox/X1Datalog.proto\"\xe9\x06\n\x0c\x41ppX1Command\x12\x34\n\x07general\x18\x01 \x01(\x0e\x32!.ctl.iox.AppX1Command.CommandTypeH\x00\x12\x36\n\tcalibrate\x18\x02 \x01(\x0b\x32!.ctl.iox.AppX1Command.CalibrationH\x00\x12\x30\n\x07\x64\x65\x62ugio\x18\x03 \x01(\x0b\x32\x1d.ctl.iox.AppX1Command.DebugIoH\x00\x12;\n\rdatalog_erase\x18\x04 \x01(\x0b\x32\".ctl.iox.AppX1Command.DatalogEraseH\x00\x12:\n\x0c\x61uthenticate\x18\x05 \x01(\x0b\x32\".ctl.iox.AppX1Command.AuthenticateH\x00\x1ag\n\x0b\x43\x61libration\x12,\n\x04mode\x18\x01 \x01(\x0e\x32\x1e.ctl.iox.Gatt.Calibration.Mode\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\r\x12\x11\n\tgas_label\x18\x03 \x03(\t\x1a\x1a\n\x07\x44\x65\x62ugIo\x12\x0f\n\x07message\x18\x01 \x01(\t\x1a<\n\x0c\x44\x61talogErase\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.ctl.iox.X1Datalog.DatalogType\x1a@\n\x0c\x41uthenticate\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x1e\n\x16\x61uthentication_timeout\x18\x02 \x01(\r\"\xaf\x02\n\x0b\x43ommandType\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0c\x45NTER_CONFIG\x10\x01\x12\x0f\n\x0b\x45XIT_CONFIG\x10\x02\x12\x0c\n\x08\x45VAC_SET\x10\x03\x12\x0e\n\nEVAC_CLEAR\x10\x04\x12\x12\n\x0eRESTART_CONFIG\x10\x05\x12\r\n\tSYNC_TIME\x10\x06\x12\x12\n\x0e\x43LEAR_PASSWORD\x10\x07\x12\r\n\tENTER_CAL\x10\x08\x12\x0c\n\x08\x45XIT_CAL\x10\t\x12\x12\n\x0e\x45NTER_BOOTLOAD\x10\n\x12\x12\n\x0eGET_DIAGNOSTIC\x10\x0b\x12\x14\n\x10\x45NTER_PRODUCTION\x10\x0c\x12\x13\n\x0f\x45XIT_PRODUCTION\x10\r\x12\x15\n\x11NETWORK_ALARM_SET\x10\x0e\x12\x17\n\x13NETWORK_ALARM_CLEAR\x10\x0f\x42\t\n\x07\x63ommandb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_AppX1Gatt__pb2.DESCRIPTOR,ctl_dot_iox_dot_X1Datalog__pb2.DESCRIPTOR,])



_APPX1COMMAND_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='ctl.iox.AppX1Command.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_CONFIG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVAC_SET', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVAC_CLEAR', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESTART_CONFIG', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SYNC_TIME', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLEAR_PASSWORD', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_CAL', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_CAL', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_BOOTLOAD', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GET_DIAGNOSTIC', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENTER_PRODUCTION', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXIT_PRODUCTION', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NETWORK_ALARM_SET', index=14, number=14,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NETWORK_ALARM_CLEAR', index=15, number=15,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=649,
  serialized_end=952,
)
_sym_db.RegisterEnumDescriptor(_APPX1COMMAND_COMMANDTYPE)


_APPX1COMMAND_CALIBRATION = _descriptor.Descriptor(
  name='Calibration',
  full_name='ctl.iox.AppX1Command.Calibration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ctl.iox.AppX1Command.Calibration.mode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout_seconds', full_name='ctl.iox.AppX1Command.Calibration.timeout_seconds', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_label', full_name='ctl.iox.AppX1Command.Calibration.gas_label', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=490,
)

_APPX1COMMAND_DEBUGIO = _descriptor.Descriptor(
  name='DebugIo',
  full_name='ctl.iox.AppX1Command.DebugIo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ctl.iox.AppX1Command.DebugIo.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=518,
)

_APPX1COMMAND_DATALOGERASE = _descriptor.Descriptor(
  name='DatalogErase',
  full_name='ctl.iox.AppX1Command.DatalogErase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ctl.iox.AppX1Command.DatalogErase.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=580,
)

_APPX1COMMAND_AUTHENTICATE = _descriptor.Descriptor(
  name='Authenticate',
  full_name='ctl.iox.AppX1Command.Authenticate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='ctl.iox.AppX1Command.Authenticate.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_timeout', full_name='ctl.iox.AppX1Command.Authenticate.authentication_timeout', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=646,
)

_APPX1COMMAND = _descriptor.Descriptor(
  name='AppX1Command',
  full_name='ctl.iox.AppX1Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='general', full_name='ctl.iox.AppX1Command.general', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calibrate', full_name='ctl.iox.AppX1Command.calibrate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debugio', full_name='ctl.iox.AppX1Command.debugio', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datalog_erase', full_name='ctl.iox.AppX1Command.datalog_erase', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authenticate', full_name='ctl.iox.AppX1Command.authenticate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPX1COMMAND_CALIBRATION, _APPX1COMMAND_DEBUGIO, _APPX1COMMAND_DATALOGERASE, _APPX1COMMAND_AUTHENTICATE, ],
  enum_types=[
    _APPX1COMMAND_COMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='ctl.iox.AppX1Command.command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=90,
  serialized_end=963,
)

_APPX1COMMAND_CALIBRATION.fields_by_name['mode'].enum_type = ctl_dot_iox_dot_AppX1Gatt__pb2._GATT_CALIBRATION_MODE
_APPX1COMMAND_CALIBRATION.containing_type = _APPX1COMMAND
_APPX1COMMAND_DEBUGIO.containing_type = _APPX1COMMAND
_APPX1COMMAND_DATALOGERASE.fields_by_name['type'].enum_type = ctl_dot_iox_dot_X1Datalog__pb2._X1DATALOG_DATALOGTYPE
_APPX1COMMAND_DATALOGERASE.containing_type = _APPX1COMMAND
_APPX1COMMAND_AUTHENTICATE.containing_type = _APPX1COMMAND
_APPX1COMMAND.fields_by_name['general'].enum_type = _APPX1COMMAND_COMMANDTYPE
_APPX1COMMAND.fields_by_name['calibrate'].message_type = _APPX1COMMAND_CALIBRATION
_APPX1COMMAND.fields_by_name['debugio'].message_type = _APPX1COMMAND_DEBUGIO
_APPX1COMMAND.fields_by_name['datalog_erase'].message_type = _APPX1COMMAND_DATALOGERASE
_APPX1COMMAND.fields_by_name['authenticate'].message_type = _APPX1COMMAND_AUTHENTICATE
_APPX1COMMAND_COMMANDTYPE.containing_type = _APPX1COMMAND
_APPX1COMMAND.oneofs_by_name['command'].fields.append(
  _APPX1COMMAND.fields_by_name['general'])
_APPX1COMMAND.fields_by_name['general'].containing_oneof = _APPX1COMMAND.oneofs_by_name['command']
_APPX1COMMAND.oneofs_by_name['command'].fields.append(
  _APPX1COMMAND.fields_by_name['calibrate'])
_APPX1COMMAND.fields_by_name['calibrate'].containing_oneof = _APPX1COMMAND.oneofs_by_name['command']
_APPX1COMMAND.oneofs_by_name['command'].fields.append(
  _APPX1COMMAND.fields_by_name['debugio'])
_APPX1COMMAND.fields_by_name['debugio'].containing_oneof = _APPX1COMMAND.oneofs_by_name['command']
_APPX1COMMAND.oneofs_by_name['command'].fields.append(
  _APPX1COMMAND.fields_by_name['datalog_erase'])
_APPX1COMMAND.fields_by_name['datalog_erase'].containing_oneof = _APPX1COMMAND.oneofs_by_name['command']
_APPX1COMMAND.oneofs_by_name['command'].fields.append(
  _APPX1COMMAND.fields_by_name['authenticate'])
_APPX1COMMAND.fields_by_name['authenticate'].containing_oneof = _APPX1COMMAND.oneofs_by_name['command']
DESCRIPTOR.message_types_by_name['AppX1Command'] = _APPX1COMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppX1Command = _reflection.GeneratedProtocolMessageType('AppX1Command', (_message.Message,), {

  'Calibration' : _reflection.GeneratedProtocolMessageType('Calibration', (_message.Message,), {
    'DESCRIPTOR' : _APPX1COMMAND_CALIBRATION,
    '__module__' : 'ctl.iox.AppX1Command_pb2'
    # @@protoc_insertion_point(class_scope:ctl.iox.AppX1Command.Calibration)
    })
  ,

  'DebugIo' : _reflection.GeneratedProtocolMessageType('DebugIo', (_message.Message,), {
    'DESCRIPTOR' : _APPX1COMMAND_DEBUGIO,
    '__module__' : 'ctl.iox.AppX1Command_pb2'
    # @@protoc_insertion_point(class_scope:ctl.iox.AppX1Command.DebugIo)
    })
  ,

  'DatalogErase' : _reflection.GeneratedProtocolMessageType('DatalogErase', (_message.Message,), {
    'DESCRIPTOR' : _APPX1COMMAND_DATALOGERASE,
    '__module__' : 'ctl.iox.AppX1Command_pb2'
    # @@protoc_insertion_point(class_scope:ctl.iox.AppX1Command.DatalogErase)
    })
  ,

  'Authenticate' : _reflection.GeneratedProtocolMessageType('Authenticate', (_message.Message,), {
    'DESCRIPTOR' : _APPX1COMMAND_AUTHENTICATE,
    '__module__' : 'ctl.iox.AppX1Command_pb2'
    # @@protoc_insertion_point(class_scope:ctl.iox.AppX1Command.Authenticate)
    })
  ,
  'DESCRIPTOR' : _APPX1COMMAND,
  '__module__' : 'ctl.iox.AppX1Command_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.AppX1Command)
  })
_sym_db.RegisterMessage(AppX1Command)
_sym_db.RegisterMessage(AppX1Command.Calibration)
_sym_db.RegisterMessage(AppX1Command.DebugIo)
_sym_db.RegisterMessage(AppX1Command.DatalogErase)
_sym_db.RegisterMessage(AppX1Command.Authenticate)


# @@protoc_insertion_point(module_scope)
