# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/battery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/battery.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63tl/iox/battery.proto\x12\x07\x63tl.iox\"t\n\rBatteryRecord\x12\x12\n\npercentage\x18\x01 \x01(\r\x12\x15\n\rtime_to_empty\x18\x02 \x01(\r\x12\x1a\n\x12remaining_capacity\x18\x03 \x01(\r\x12\x1c\n\x14\x66ull_charge_capacity\x18\x04 \x01(\rb\x06proto3')
)




_BATTERYRECORD = _descriptor.Descriptor(
  name='BatteryRecord',
  full_name='ctl.iox.BatteryRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='percentage', full_name='ctl.iox.BatteryRecord.percentage', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_to_empty', full_name='ctl.iox.BatteryRecord.time_to_empty', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remaining_capacity', full_name='ctl.iox.BatteryRecord.remaining_capacity', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_charge_capacity', full_name='ctl.iox.BatteryRecord.full_charge_capacity', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['BatteryRecord'] = _BATTERYRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BatteryRecord = _reflection.GeneratedProtocolMessageType('BatteryRecord', (_message.Message,), {
  'DESCRIPTOR' : _BATTERYRECORD,
  '__module__' : 'ctl.iox.battery_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.BatteryRecord)
  })
_sym_db.RegisterMessage(BatteryRecord)


# @@protoc_insertion_point(module_scope)
