# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/cal_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_calibration_data_pb2 as ctl_dot_iox_dot_dock__calibration__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/cal_record.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x63tl/iox/cal_record.proto\x12\x07\x63tl.iox\x1a#ctl/iox/dock_calibration_data.proto\"\xa9\x01\n\tCalRecord\x12L\n\x1e\x64ock_calibration_data_response\x18\x01 \x01(\x0b\x32$.ctl.iox.DockCalibrationDataResponse\x12\x35\n\x12sensor_test_record\x18\x02 \x03(\x0b\x32\x19.ctl.iox.SensorTestRecord\x12\x17\n\x0ftime_valve_open\x18\x03 \x03(\x05\"\x85\x02\n\x10SensorTestRecord\x12\x18\n\x10\x65xpected_reading\x18\x01 \x01(\x05\x12\x18\n\x10observed_reading\x18\x02 \x01(\x05\x12#\n\x06result\x18\x03 \x01(\x0e\x32\x13.ctl.iox.TestResult\x12$\n\ttest_type\x18\x04 \x01(\x0e\x32\x11.ctl.iox.TestType\x12\x12\n\nspan_value\x18\x05 \x01(\x05\x12\x12\n\nzero_value\x18\x06 \x01(\x05\x12\x1e\n\x16zero_compensator_value\x18\x07 \x01(\x05\x12\x12\n\nbead_state\x18\x08 \x01(\x08\x12\x16\n\x0e\x63ylinder_index\x18\t \x01(\x05*m\n\x08TestType\x12\x12\n\x0eTEST_TYPE_NONE\x10\x00\x12\x12\n\x0eTEST_TYPE_ZERO\x10\x01\x12\x12\n\x0eTEST_TYPE_SPAN\x10\x02\x12\x12\n\x0eTEST_TYPE_BUMP\x10\x03\x12\x11\n\rTEST_TYPE_FAS\x10\x04*\xcf\x01\n\nTestResult\x12\x1a\n\x16TEST_RESULT_NOT_TESTED\x10\x00\x12\x14\n\x10TEST_RESULT_PASS\x10\x01\x12\x14\n\x10TEST_RESULT_FAIL\x10\x02\x12 \n\x1cTEST_RESULT_LIFE_HEALTH_WARN\x10\x03\x12!\n\x1dTEST_RESULT_LIFE_HEALTH_ALARM\x10\x04\x12\x17\n\x13TEST_RESULT_SKIPPED\x10\x05\x12\x1b\n\x17TEST_RESULT_IN_PROGRESS\x10\x06\x62\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__calibration__data__pb2.DESCRIPTOR,])

_TESTTYPE = _descriptor.EnumDescriptor(
  name='TestType',
  full_name='ctl.iox.TestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST_TYPE_NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_TYPE_ZERO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_TYPE_SPAN', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_TYPE_BUMP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_TYPE_FAS', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=510,
  serialized_end=619,
)
_sym_db.RegisterEnumDescriptor(_TESTTYPE)

TestType = enum_type_wrapper.EnumTypeWrapper(_TESTTYPE)
_TESTRESULT = _descriptor.EnumDescriptor(
  name='TestResult',
  full_name='ctl.iox.TestResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_NOT_TESTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_PASS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_FAIL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_LIFE_HEALTH_WARN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_LIFE_HEALTH_ALARM', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_SKIPPED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST_RESULT_IN_PROGRESS', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=622,
  serialized_end=829,
)
_sym_db.RegisterEnumDescriptor(_TESTRESULT)

TestResult = enum_type_wrapper.EnumTypeWrapper(_TESTRESULT)
TEST_TYPE_NONE = 0
TEST_TYPE_ZERO = 1
TEST_TYPE_SPAN = 2
TEST_TYPE_BUMP = 3
TEST_TYPE_FAS = 4
TEST_RESULT_NOT_TESTED = 0
TEST_RESULT_PASS = 1
TEST_RESULT_FAIL = 2
TEST_RESULT_LIFE_HEALTH_WARN = 3
TEST_RESULT_LIFE_HEALTH_ALARM = 4
TEST_RESULT_SKIPPED = 5
TEST_RESULT_IN_PROGRESS = 6



_CALRECORD = _descriptor.Descriptor(
  name='CalRecord',
  full_name='ctl.iox.CalRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dock_calibration_data_response', full_name='ctl.iox.CalRecord.dock_calibration_data_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_test_record', full_name='ctl.iox.CalRecord.sensor_test_record', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_valve_open', full_name='ctl.iox.CalRecord.time_valve_open', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=244,
)


_SENSORTESTRECORD = _descriptor.Descriptor(
  name='SensorTestRecord',
  full_name='ctl.iox.SensorTestRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expected_reading', full_name='ctl.iox.SensorTestRecord.expected_reading', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observed_reading', full_name='ctl.iox.SensorTestRecord.observed_reading', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='ctl.iox.SensorTestRecord.result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_type', full_name='ctl.iox.SensorTestRecord.test_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='span_value', full_name='ctl.iox.SensorTestRecord.span_value', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zero_value', full_name='ctl.iox.SensorTestRecord.zero_value', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zero_compensator_value', full_name='ctl.iox.SensorTestRecord.zero_compensator_value', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bead_state', full_name='ctl.iox.SensorTestRecord.bead_state', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinder_index', full_name='ctl.iox.SensorTestRecord.cylinder_index', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=508,
)

_CALRECORD.fields_by_name['dock_calibration_data_response'].message_type = ctl_dot_iox_dot_dock__calibration__data__pb2._DOCKCALIBRATIONDATARESPONSE
_CALRECORD.fields_by_name['sensor_test_record'].message_type = _SENSORTESTRECORD
_SENSORTESTRECORD.fields_by_name['result'].enum_type = _TESTRESULT
_SENSORTESTRECORD.fields_by_name['test_type'].enum_type = _TESTTYPE
DESCRIPTOR.message_types_by_name['CalRecord'] = _CALRECORD
DESCRIPTOR.message_types_by_name['SensorTestRecord'] = _SENSORTESTRECORD
DESCRIPTOR.enum_types_by_name['TestType'] = _TESTTYPE
DESCRIPTOR.enum_types_by_name['TestResult'] = _TESTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CalRecord = _reflection.GeneratedProtocolMessageType('CalRecord', (_message.Message,), {
  'DESCRIPTOR' : _CALRECORD,
  '__module__' : 'ctl.iox.cal_record_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.CalRecord)
  })
_sym_db.RegisterMessage(CalRecord)

SensorTestRecord = _reflection.GeneratedProtocolMessageType('SensorTestRecord', (_message.Message,), {
  'DESCRIPTOR' : _SENSORTESTRECORD,
  '__module__' : 'ctl.iox.cal_record_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.SensorTestRecord)
  })
_sym_db.RegisterMessage(SensorTestRecord)


# @@protoc_insertion_point(module_scope)
