# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/cico.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import tag_pb2 as ctl_dot_iox_dot_tag__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/cico.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63tl/iox/cico.proto\x12\x07\x63tl.iox\x1a\x11\x63tl/iox/tag.proto\"\x0f\n\rGenericMsaTag\"\x11\n\x0fGenericOtherTag\"\xac\x01\n\tTagRecord\x12\x0f\n\x07tag_uid\x18\x01 \x01(\x0c\x12\x10\n\x08tag_data\x18\x02 \x01(\x0c\x12\"\n\x03muc\x18\n \x01(\x0b\x32\x13.ctl.iox.MucPayloadH\x00\x12%\n\x03msa\x18\x0b \x01(\x0b\x32\x16.ctl.iox.GenericMsaTagH\x00\x12)\n\x05other\x18\x0c \x01(\x0b\x32\x18.ctl.iox.GenericOtherTagH\x00\x42\x06\n\x04\x64\x61ta\",\n\x15RemoteCheckoutRequest\x12\x13\n\x0b\x61ssigned_to\x18\x01 \x01(\t\"\x16\n\x14RemoteCheckinRequestb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_tag__pb2.DESCRIPTOR,])




_GENERICMSATAG = _descriptor.Descriptor(
  name='GenericMsaTag',
  full_name='ctl.iox.GenericMsaTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=65,
)


_GENERICOTHERTAG = _descriptor.Descriptor(
  name='GenericOtherTag',
  full_name='ctl.iox.GenericOtherTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=84,
)


_TAGRECORD = _descriptor.Descriptor(
  name='TagRecord',
  full_name='ctl.iox.TagRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_uid', full_name='ctl.iox.TagRecord.tag_uid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag_data', full_name='ctl.iox.TagRecord.tag_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='muc', full_name='ctl.iox.TagRecord.muc', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msa', full_name='ctl.iox.TagRecord.msa', index=3,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='other', full_name='ctl.iox.TagRecord.other', index=4,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='ctl.iox.TagRecord.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=87,
  serialized_end=259,
)


_REMOTECHECKOUTREQUEST = _descriptor.Descriptor(
  name='RemoteCheckoutRequest',
  full_name='ctl.iox.RemoteCheckoutRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='assigned_to', full_name='ctl.iox.RemoteCheckoutRequest.assigned_to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=305,
)


_REMOTECHECKINREQUEST = _descriptor.Descriptor(
  name='RemoteCheckinRequest',
  full_name='ctl.iox.RemoteCheckinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=329,
)

_TAGRECORD.fields_by_name['muc'].message_type = ctl_dot_iox_dot_tag__pb2._MUCPAYLOAD
_TAGRECORD.fields_by_name['msa'].message_type = _GENERICMSATAG
_TAGRECORD.fields_by_name['other'].message_type = _GENERICOTHERTAG
_TAGRECORD.oneofs_by_name['data'].fields.append(
  _TAGRECORD.fields_by_name['muc'])
_TAGRECORD.fields_by_name['muc'].containing_oneof = _TAGRECORD.oneofs_by_name['data']
_TAGRECORD.oneofs_by_name['data'].fields.append(
  _TAGRECORD.fields_by_name['msa'])
_TAGRECORD.fields_by_name['msa'].containing_oneof = _TAGRECORD.oneofs_by_name['data']
_TAGRECORD.oneofs_by_name['data'].fields.append(
  _TAGRECORD.fields_by_name['other'])
_TAGRECORD.fields_by_name['other'].containing_oneof = _TAGRECORD.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['GenericMsaTag'] = _GENERICMSATAG
DESCRIPTOR.message_types_by_name['GenericOtherTag'] = _GENERICOTHERTAG
DESCRIPTOR.message_types_by_name['TagRecord'] = _TAGRECORD
DESCRIPTOR.message_types_by_name['RemoteCheckoutRequest'] = _REMOTECHECKOUTREQUEST
DESCRIPTOR.message_types_by_name['RemoteCheckinRequest'] = _REMOTECHECKINREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenericMsaTag = _reflection.GeneratedProtocolMessageType('GenericMsaTag', (_message.Message,), {
  'DESCRIPTOR' : _GENERICMSATAG,
  '__module__' : 'ctl.iox.cico_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.GenericMsaTag)
  })
_sym_db.RegisterMessage(GenericMsaTag)

GenericOtherTag = _reflection.GeneratedProtocolMessageType('GenericOtherTag', (_message.Message,), {
  'DESCRIPTOR' : _GENERICOTHERTAG,
  '__module__' : 'ctl.iox.cico_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.GenericOtherTag)
  })
_sym_db.RegisterMessage(GenericOtherTag)

TagRecord = _reflection.GeneratedProtocolMessageType('TagRecord', (_message.Message,), {
  'DESCRIPTOR' : _TAGRECORD,
  '__module__' : 'ctl.iox.cico_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.TagRecord)
  })
_sym_db.RegisterMessage(TagRecord)

RemoteCheckoutRequest = _reflection.GeneratedProtocolMessageType('RemoteCheckoutRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECHECKOUTREQUEST,
  '__module__' : 'ctl.iox.cico_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.RemoteCheckoutRequest)
  })
_sym_db.RegisterMessage(RemoteCheckoutRequest)

RemoteCheckinRequest = _reflection.GeneratedProtocolMessageType('RemoteCheckinRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECHECKINREQUEST,
  '__module__' : 'ctl.iox.cico_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.RemoteCheckinRequest)
  })
_sym_db.RegisterMessage(RemoteCheckinRequest)


# @@protoc_insertion_point(module_scope)
