# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/cloud_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import pf_instrument_config_pb2 as ctl_dot_iox_dot_pf__instrument__config__pb2
from ctl.iox import alarm_pb2 as ctl_dot_iox_dot_alarm__pb2
from ctl.iox import cico_pb2 as ctl_dot_iox_dot_cico__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/cloud_wrapper.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x63tl/iox/cloud_wrapper.proto\x12\x07\x63tl.iox\x1a\"ctl/iox/pf_instrument_config.proto\x1a\x13\x63tl/iox/alarm.proto\x1a\x12\x63tl/iox/cico.proto\"\xa5\x02\n\x0c\x43loudWrapper\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12+\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x19.ctl.iox.InstrumentConfigH\x00\x12-\n\talarm_set\x18\x04 \x01(\x0b\x32\x18.ctl.iox.AlarmRequestSetH\x00\x12\x31\n\x0b\x61larm_clear\x18\x05 \x01(\x0b\x32\x1a.ctl.iox.AlarmRequestClearH\x00\x12\x32\n\x08\x63heckout\x18\x06 \x01(\x0b\x32\x1e.ctl.iox.RemoteCheckoutRequestH\x00\x12\x30\n\x07\x63heckin\x18\x07 \x01(\x0b\x32\x1d.ctl.iox.RemoteCheckinRequestH\x00\x42\x06\n\x04\x64\x61taJ\x04\x08\x03\x10\x04\x62\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_pf__instrument__config__pb2.DESCRIPTOR,ctl_dot_iox_dot_alarm__pb2.DESCRIPTOR,ctl_dot_iox_dot_cico__pb2.DESCRIPTOR,])




_CLOUDWRAPPER = _descriptor.Descriptor(
  name='CloudWrapper',
  full_name='ctl.iox.CloudWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='ctl.iox.CloudWrapper.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='ctl.iox.CloudWrapper.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_set', full_name='ctl.iox.CloudWrapper.alarm_set', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_clear', full_name='ctl.iox.CloudWrapper.alarm_clear', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkout', full_name='ctl.iox.CloudWrapper.checkout', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='checkin', full_name='ctl.iox.CloudWrapper.checkin', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='ctl.iox.CloudWrapper.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=118,
  serialized_end=411,
)

_CLOUDWRAPPER.fields_by_name['config'].message_type = ctl_dot_iox_dot_pf__instrument__config__pb2._INSTRUMENTCONFIG
_CLOUDWRAPPER.fields_by_name['alarm_set'].message_type = ctl_dot_iox_dot_alarm__pb2._ALARMREQUESTSET
_CLOUDWRAPPER.fields_by_name['alarm_clear'].message_type = ctl_dot_iox_dot_alarm__pb2._ALARMREQUESTCLEAR
_CLOUDWRAPPER.fields_by_name['checkout'].message_type = ctl_dot_iox_dot_cico__pb2._REMOTECHECKOUTREQUEST
_CLOUDWRAPPER.fields_by_name['checkin'].message_type = ctl_dot_iox_dot_cico__pb2._REMOTECHECKINREQUEST
_CLOUDWRAPPER.oneofs_by_name['data'].fields.append(
  _CLOUDWRAPPER.fields_by_name['config'])
_CLOUDWRAPPER.fields_by_name['config'].containing_oneof = _CLOUDWRAPPER.oneofs_by_name['data']
_CLOUDWRAPPER.oneofs_by_name['data'].fields.append(
  _CLOUDWRAPPER.fields_by_name['alarm_set'])
_CLOUDWRAPPER.fields_by_name['alarm_set'].containing_oneof = _CLOUDWRAPPER.oneofs_by_name['data']
_CLOUDWRAPPER.oneofs_by_name['data'].fields.append(
  _CLOUDWRAPPER.fields_by_name['alarm_clear'])
_CLOUDWRAPPER.fields_by_name['alarm_clear'].containing_oneof = _CLOUDWRAPPER.oneofs_by_name['data']
_CLOUDWRAPPER.oneofs_by_name['data'].fields.append(
  _CLOUDWRAPPER.fields_by_name['checkout'])
_CLOUDWRAPPER.fields_by_name['checkout'].containing_oneof = _CLOUDWRAPPER.oneofs_by_name['data']
_CLOUDWRAPPER.oneofs_by_name['data'].fields.append(
  _CLOUDWRAPPER.fields_by_name['checkin'])
_CLOUDWRAPPER.fields_by_name['checkin'].containing_oneof = _CLOUDWRAPPER.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['CloudWrapper'] = _CLOUDWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloudWrapper = _reflection.GeneratedProtocolMessageType('CloudWrapper', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDWRAPPER,
  '__module__' : 'ctl.iox.cloud_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.CloudWrapper)
  })
_sym_db.RegisterMessage(CloudWrapper)


# @@protoc_insertion_point(module_scope)
