# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/connectivity.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl import version_pb2 as ctl_dot_version__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/connectivity.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63tl/iox/connectivity.proto\x12\x07\x63tl.iox\x1a\x11\x63tl/version.proto\"m\n\x0f\x43onnectivityMsg\x12$\n\x05state\x18\x01 \x01(\x0e\x32\x15.ctl.iox.Connectivity\x12\x15\n\rconnection_id\x18\x02 \x01(\r\x12\x1d\n\x07version\x18\x03 \x01(\x0b\x32\x0c.ctl.Version*`\n\x0c\x43onnectivity\x12\x1a\n\x16\x43ONNECTIVITY_CONNECTED\x10\x00\x12\x1d\n\x19\x43ONNECTIVITY_DISCONNECTED\x10\x01\x12\x15\n\x11\x43ONNECTIVITY_LOST\x10\x02\x62\x06proto3')
  ,
  dependencies=[ctl_dot_version__pb2.DESCRIPTOR,])

_CONNECTIVITY = _descriptor.EnumDescriptor(
  name='Connectivity',
  full_name='ctl.iox.Connectivity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECTIVITY_CONNECTED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTIVITY_DISCONNECTED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTIVITY_LOST', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=169,
  serialized_end=265,
)
_sym_db.RegisterEnumDescriptor(_CONNECTIVITY)

Connectivity = enum_type_wrapper.EnumTypeWrapper(_CONNECTIVITY)
CONNECTIVITY_CONNECTED = 0
CONNECTIVITY_DISCONNECTED = 1
CONNECTIVITY_LOST = 2



_CONNECTIVITYMSG = _descriptor.Descriptor(
  name='ConnectivityMsg',
  full_name='ctl.iox.ConnectivityMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='ctl.iox.ConnectivityMsg.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connection_id', full_name='ctl.iox.ConnectivityMsg.connection_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='ctl.iox.ConnectivityMsg.version', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=167,
)

_CONNECTIVITYMSG.fields_by_name['state'].enum_type = _CONNECTIVITY
_CONNECTIVITYMSG.fields_by_name['version'].message_type = ctl_dot_version__pb2._VERSION
DESCRIPTOR.message_types_by_name['ConnectivityMsg'] = _CONNECTIVITYMSG
DESCRIPTOR.enum_types_by_name['Connectivity'] = _CONNECTIVITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectivityMsg = _reflection.GeneratedProtocolMessageType('ConnectivityMsg', (_message.Message,), {
  'DESCRIPTOR' : _CONNECTIVITYMSG,
  '__module__' : 'ctl.iox.connectivity_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.ConnectivityMsg)
  })
_sym_db.RegisterMessage(ConnectivityMsg)


# @@protoc_insertion_point(module_scope)
