# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_shared_pb2 as ctl_dot_iox_dot_dock__shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_configuration.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n ctl/iox/dock_configuration.proto\x12\x07\x63tl.iox\x1a\x19\x63tl/iox/dock_shared.proto\"Q\n\x18\x44ockConfigurationRequest\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12(\n\x0b\x64ock_config\x18\x02 \x01(\x0b\x32\x13.ctl.iox.DockConfig\"R\n\x19\x44ockConfigurationResponse\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12(\n\x0b\x64ock_config\x18\x02 \x01(\x0b\x32\x13.ctl.iox.DockConfigb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__shared__pb2.DESCRIPTOR,])




_DOCKCONFIGURATIONREQUEST = _descriptor.Descriptor(
  name='DockConfigurationRequest',
  full_name='ctl.iox.DockConfigurationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.DockConfigurationRequest.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_config', full_name='ctl.iox.DockConfigurationRequest.dock_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=153,
)


_DOCKCONFIGURATIONRESPONSE = _descriptor.Descriptor(
  name='DockConfigurationResponse',
  full_name='ctl.iox.DockConfigurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.DockConfigurationResponse.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_config', full_name='ctl.iox.DockConfigurationResponse.dock_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=237,
)

_DOCKCONFIGURATIONREQUEST.fields_by_name['dock_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._DOCKCONFIG
_DOCKCONFIGURATIONRESPONSE.fields_by_name['dock_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._DOCKCONFIG
DESCRIPTOR.message_types_by_name['DockConfigurationRequest'] = _DOCKCONFIGURATIONREQUEST
DESCRIPTOR.message_types_by_name['DockConfigurationResponse'] = _DOCKCONFIGURATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockConfigurationRequest = _reflection.GeneratedProtocolMessageType('DockConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCONFIGURATIONREQUEST,
  '__module__' : 'ctl.iox.dock_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockConfigurationRequest)
  })
_sym_db.RegisterMessage(DockConfigurationRequest)

DockConfigurationResponse = _reflection.GeneratedProtocolMessageType('DockConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCONFIGURATIONRESPONSE,
  '__module__' : 'ctl.iox.dock_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockConfigurationResponse)
  })
_sym_db.RegisterMessage(DockConfigurationResponse)


# @@protoc_insertion_point(module_scope)
