# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_scan_wifi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_scan_wifi.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x63tl/iox/dock_scan_wifi.proto\x12\x07\x63tl.iox\"\x15\n\x13\x44ockScanWifiRequest\">\n\x0b\x41\x63\x63\x65ssPoint\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08strength\x18\x02 \x01(\r\x12\x0f\n\x07secured\x18\x03 \x01(\x08\"B\n\x14\x44ockScanWifiResponse\x12*\n\x0c\x61\x63\x63\x65sspoints\x18\x01 \x03(\x0b\x32\x14.ctl.iox.AccessPointb\x06proto3')
)




_DOCKSCANWIFIREQUEST = _descriptor.Descriptor(
  name='DockScanWifiRequest',
  full_name='ctl.iox.DockScanWifiRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=62,
)


_ACCESSPOINT = _descriptor.Descriptor(
  name='AccessPoint',
  full_name='ctl.iox.AccessPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssid', full_name='ctl.iox.AccessPoint.ssid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strength', full_name='ctl.iox.AccessPoint.strength', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secured', full_name='ctl.iox.AccessPoint.secured', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=126,
)


_DOCKSCANWIFIRESPONSE = _descriptor.Descriptor(
  name='DockScanWifiResponse',
  full_name='ctl.iox.DockScanWifiResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accesspoints', full_name='ctl.iox.DockScanWifiResponse.accesspoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=194,
)

_DOCKSCANWIFIRESPONSE.fields_by_name['accesspoints'].message_type = _ACCESSPOINT
DESCRIPTOR.message_types_by_name['DockScanWifiRequest'] = _DOCKSCANWIFIREQUEST
DESCRIPTOR.message_types_by_name['AccessPoint'] = _ACCESSPOINT
DESCRIPTOR.message_types_by_name['DockScanWifiResponse'] = _DOCKSCANWIFIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockScanWifiRequest = _reflection.GeneratedProtocolMessageType('DockScanWifiRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKSCANWIFIREQUEST,
  '__module__' : 'ctl.iox.dock_scan_wifi_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockScanWifiRequest)
  })
_sym_db.RegisterMessage(DockScanWifiRequest)

AccessPoint = _reflection.GeneratedProtocolMessageType('AccessPoint', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSPOINT,
  '__module__' : 'ctl.iox.dock_scan_wifi_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.AccessPoint)
  })
_sym_db.RegisterMessage(AccessPoint)

DockScanWifiResponse = _reflection.GeneratedProtocolMessageType('DockScanWifiResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKSCANWIFIRESPONSE,
  '__module__' : 'ctl.iox.dock_scan_wifi_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockScanWifiResponse)
  })
_sym_db.RegisterMessage(DockScanWifiResponse)


# @@protoc_insertion_point(module_scope)
