# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_time_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_time_config.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1e\x63tl/iox/dock_time_config.proto\x12\x07\x63tl.iox\":\n\x15\x44ockTimeConfigRequest\x12\x0f\n\x07utcTime\x18\x01 \x01(\x04\x12\x10\n\x08utcDelta\x18\x02 \x01(\x11\")\n\x16\x44ockTimeConfigResponse\x12\x0f\n\x07utcTime\x18\x01 \x01(\x04\x62\x06proto3')
)




_DOCKTIMECONFIGREQUEST = _descriptor.Descriptor(
  name='DockTimeConfigRequest',
  full_name='ctl.iox.DockTimeConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utcTime', full_name='ctl.iox.DockTimeConfigRequest.utcTime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='utcDelta', full_name='ctl.iox.DockTimeConfigRequest.utcDelta', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=101,
)


_DOCKTIMECONFIGRESPONSE = _descriptor.Descriptor(
  name='DockTimeConfigResponse',
  full_name='ctl.iox.DockTimeConfigResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utcTime', full_name='ctl.iox.DockTimeConfigResponse.utcTime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['DockTimeConfigRequest'] = _DOCKTIMECONFIGREQUEST
DESCRIPTOR.message_types_by_name['DockTimeConfigResponse'] = _DOCKTIMECONFIGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockTimeConfigRequest = _reflection.GeneratedProtocolMessageType('DockTimeConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKTIMECONFIGREQUEST,
  '__module__' : 'ctl.iox.dock_time_config_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockTimeConfigRequest)
  })
_sym_db.RegisterMessage(DockTimeConfigRequest)

DockTimeConfigResponse = _reflection.GeneratedProtocolMessageType('DockTimeConfigResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKTIMECONFIGRESPONSE,
  '__module__' : 'ctl.iox.dock_time_config_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockTimeConfigResponse)
  })
_sym_db.RegisterMessage(DockTimeConfigResponse)


# @@protoc_insertion_point(module_scope)
