# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_bank_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_shared_pb2 as ctl_dot_iox_dot_dock__shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_bank_data.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1c\x63tl/iox/dock_bank_data.proto\x12\x07\x63tl.iox\x1a\x19\x63tl/iox/dock_shared.proto\"\x15\n\x13\x44ockBankDataRequest\"\x9d\x01\n\x14\x44ockBankDataResponse\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\x06\x12(\n\x0b\x62\x61nk_config\x18\x02 \x01(\x0b\x32\x13.ctl.iox.BankConfig\x12 \n\x05\x64ocks\x18\x03 \x03(\x0b\x32\x11.ctl.iox.DockData\x12(\n\tcylinders\x18\x04 \x03(\x0b\x32\x15.ctl.iox.CylinderDatab\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__shared__pb2.DESCRIPTOR,])




_DOCKBANKDATAREQUEST = _descriptor.Descriptor(
  name='DockBankDataRequest',
  full_name='ctl.iox.DockBankDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=89,
)


_DOCKBANKDATARESPONSE = _descriptor.Descriptor(
  name='DockBankDataResponse',
  full_name='ctl.iox.DockBankDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bank_id', full_name='ctl.iox.DockBankDataResponse.bank_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bank_config', full_name='ctl.iox.DockBankDataResponse.bank_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docks', full_name='ctl.iox.DockBankDataResponse.docks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinders', full_name='ctl.iox.DockBankDataResponse.cylinders', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=249,
)

_DOCKBANKDATARESPONSE.fields_by_name['bank_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._BANKCONFIG
_DOCKBANKDATARESPONSE.fields_by_name['docks'].message_type = ctl_dot_iox_dot_dock__shared__pb2._DOCKDATA
_DOCKBANKDATARESPONSE.fields_by_name['cylinders'].message_type = ctl_dot_iox_dot_dock__shared__pb2._CYLINDERDATA
DESCRIPTOR.message_types_by_name['DockBankDataRequest'] = _DOCKBANKDATAREQUEST
DESCRIPTOR.message_types_by_name['DockBankDataResponse'] = _DOCKBANKDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockBankDataRequest = _reflection.GeneratedProtocolMessageType('DockBankDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKBANKDATAREQUEST,
  '__module__' : 'ctl.iox.dock_bank_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockBankDataRequest)
  })
_sym_db.RegisterMessage(DockBankDataRequest)

DockBankDataResponse = _reflection.GeneratedProtocolMessageType('DockBankDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKBANKDATARESPONSE,
  '__module__' : 'ctl.iox.dock_bank_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockBankDataResponse)
  })
_sym_db.RegisterMessage(DockBankDataResponse)


# @@protoc_insertion_point(module_scope)
