# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_calibration_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_shared_pb2 as ctl_dot_iox_dot_dock__shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_calibration_data.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n#ctl/iox/dock_calibration_data.proto\x12\x07\x63tl.iox\x1a\x19\x63tl/iox/dock_shared.proto\"\x1c\n\x1a\x44ockCalibrationDataRequest\"\xe4\x02\n\x1b\x44ockCalibrationDataResponse\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\x06\x12\x10\n\x08\x64ock_ssn\x18\x02 \x01(\x0c\x12(\n\x0b\x64ock_config\x18\x03 \x01(\x0b\x32\x13.ctl.iox.DockConfig\x12(\n\x0b\x64ock_status\x18\x04 \x01(\x0b\x32\x13.ctl.iox.DockStatus\x12\x44\n\tcylinders\x18\x05 \x03(\x0b\x32\x31.ctl.iox.DockCalibrationDataResponse.CylinderData\x12\x14\n\x0c\x64ock_address\x18\x06 \x01(\r\x1ar\n\x0c\x43ylinderData\x12\x30\n\x0f\x63ylinder_config\x18\x01 \x01(\x0b\x32\x17.ctl.iox.CylinderConfig\x12\x30\n\x0f\x63ylinder_status\x18\x02 \x01(\x0b\x32\x17.ctl.iox.CylinderStatusb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__shared__pb2.DESCRIPTOR,])




_DOCKCALIBRATIONDATAREQUEST = _descriptor.Descriptor(
  name='DockCalibrationDataRequest',
  full_name='ctl.iox.DockCalibrationDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=103,
)


_DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA = _descriptor.Descriptor(
  name='CylinderData',
  full_name='ctl.iox.DockCalibrationDataResponse.CylinderData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cylinder_config', full_name='ctl.iox.DockCalibrationDataResponse.CylinderData.cylinder_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinder_status', full_name='ctl.iox.DockCalibrationDataResponse.CylinderData.cylinder_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=462,
)

_DOCKCALIBRATIONDATARESPONSE = _descriptor.Descriptor(
  name='DockCalibrationDataResponse',
  full_name='ctl.iox.DockCalibrationDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bank_id', full_name='ctl.iox.DockCalibrationDataResponse.bank_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_ssn', full_name='ctl.iox.DockCalibrationDataResponse.dock_ssn', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_config', full_name='ctl.iox.DockCalibrationDataResponse.dock_config', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_status', full_name='ctl.iox.DockCalibrationDataResponse.dock_status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinders', full_name='ctl.iox.DockCalibrationDataResponse.cylinders', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock_address', full_name='ctl.iox.DockCalibrationDataResponse.dock_address', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=462,
)

_DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA.fields_by_name['cylinder_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._CYLINDERCONFIG
_DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA.fields_by_name['cylinder_status'].message_type = ctl_dot_iox_dot_dock__shared__pb2._CYLINDERSTATUS
_DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA.containing_type = _DOCKCALIBRATIONDATARESPONSE
_DOCKCALIBRATIONDATARESPONSE.fields_by_name['dock_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._DOCKCONFIG
_DOCKCALIBRATIONDATARESPONSE.fields_by_name['dock_status'].message_type = ctl_dot_iox_dot_dock__shared__pb2._DOCKSTATUS
_DOCKCALIBRATIONDATARESPONSE.fields_by_name['cylinders'].message_type = _DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA
DESCRIPTOR.message_types_by_name['DockCalibrationDataRequest'] = _DOCKCALIBRATIONDATAREQUEST
DESCRIPTOR.message_types_by_name['DockCalibrationDataResponse'] = _DOCKCALIBRATIONDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockCalibrationDataRequest = _reflection.GeneratedProtocolMessageType('DockCalibrationDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCALIBRATIONDATAREQUEST,
  '__module__' : 'ctl.iox.dock_calibration_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockCalibrationDataRequest)
  })
_sym_db.RegisterMessage(DockCalibrationDataRequest)

DockCalibrationDataResponse = _reflection.GeneratedProtocolMessageType('DockCalibrationDataResponse', (_message.Message,), {

  'CylinderData' : _reflection.GeneratedProtocolMessageType('CylinderData', (_message.Message,), {
    'DESCRIPTOR' : _DOCKCALIBRATIONDATARESPONSE_CYLINDERDATA,
    '__module__' : 'ctl.iox.dock_calibration_data_pb2'
    # @@protoc_insertion_point(class_scope:ctl.iox.DockCalibrationDataResponse.CylinderData)
    })
  ,
  'DESCRIPTOR' : _DOCKCALIBRATIONDATARESPONSE,
  '__module__' : 'ctl.iox.dock_calibration_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockCalibrationDataResponse)
  })
_sym_db.RegisterMessage(DockCalibrationDataResponse)
_sym_db.RegisterMessage(DockCalibrationDataResponse.CylinderData)


# @@protoc_insertion_point(module_scope)
