# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_bank_configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_shared_pb2 as ctl_dot_iox_dot_dock__shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_bank_configuration.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%ctl/iox/dock_bank_configuration.proto\x12\x07\x63tl.iox\x1a\x19\x63tl/iox/dock_shared.proto\"H\n\x1c\x44ockBankConfigurationRequest\x12(\n\x0b\x62\x61nk_config\x18\x01 \x01(\x0b\x32\x13.ctl.iox.BankConfig\"Z\n\x1d\x44ockBankConfigurationResponse\x12\x0f\n\x07\x62\x61nk_id\x18\x01 \x01(\x06\x12(\n\x0b\x62\x61nk_config\x18\x02 \x01(\x0b\x32\x13.ctl.iox.BankConfigb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__shared__pb2.DESCRIPTOR,])




_DOCKBANKCONFIGURATIONREQUEST = _descriptor.Descriptor(
  name='DockBankConfigurationRequest',
  full_name='ctl.iox.DockBankConfigurationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bank_config', full_name='ctl.iox.DockBankConfigurationRequest.bank_config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=149,
)


_DOCKBANKCONFIGURATIONRESPONSE = _descriptor.Descriptor(
  name='DockBankConfigurationResponse',
  full_name='ctl.iox.DockBankConfigurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bank_id', full_name='ctl.iox.DockBankConfigurationResponse.bank_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bank_config', full_name='ctl.iox.DockBankConfigurationResponse.bank_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=241,
)

_DOCKBANKCONFIGURATIONREQUEST.fields_by_name['bank_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._BANKCONFIG
_DOCKBANKCONFIGURATIONRESPONSE.fields_by_name['bank_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._BANKCONFIG
DESCRIPTOR.message_types_by_name['DockBankConfigurationRequest'] = _DOCKBANKCONFIGURATIONREQUEST
DESCRIPTOR.message_types_by_name['DockBankConfigurationResponse'] = _DOCKBANKCONFIGURATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockBankConfigurationRequest = _reflection.GeneratedProtocolMessageType('DockBankConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKBANKCONFIGURATIONREQUEST,
  '__module__' : 'ctl.iox.dock_bank_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockBankConfigurationRequest)
  })
_sym_db.RegisterMessage(DockBankConfigurationRequest)

DockBankConfigurationResponse = _reflection.GeneratedProtocolMessageType('DockBankConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKBANKCONFIGURATIONRESPONSE,
  '__module__' : 'ctl.iox.dock_bank_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockBankConfigurationResponse)
  })
_sym_db.RegisterMessage(DockBankConfigurationResponse)


# @@protoc_insertion_point(module_scope)
