# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import readings_pb2 as ctl_dot_iox_dot_readings__pb2
from ctl.iox import cal_record_pb2 as ctl_dot_iox_dot_cal__record__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_control.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63tl/iox/dock_control.proto\x12\x07\x63tl.iox\x1a\x16\x63tl/iox/readings.proto\x1a\x18\x63tl/iox/cal_record.proto\"0\n\x0cValveControl\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x10\n\x08max_time\x18\x02 \x01(\r\"\x07\n\x05\x41\x62ort\"?\n\x07\x44isplay\x12\x16\n\x0e\x64isplay_string\x18\x01 \x01(\t\x12\x1c\n\x14radix_point_is_comma\x18\x02 \x01(\x08\"\xbc\x01\n\x0f\x44ockSensorState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x07reading\x18\x02 \x01(\x0b\x32\x10.ctl.iox.Reading\x12(\n\x0btest_result\x18\x03 \x01(\x0e\x32\x13.ctl.iox.TestResult\x12$\n\ttest_type\x18\x04 \x01(\x0e\x32\x11.ctl.iox.TestType\x12(\n\x0etarget_reading\x18\x05 \x01(\x0b\x32\x10.ctl.iox.Reading\"9\n\rDockTestState\x12(\n\x06sensor\x18\x01 \x03(\x0b\x32\x18.ctl.iox.DockSensorState\"\xbe\x01\n\x0b\x44ockControl\x12$\n\ndisplayMsg\x18\x01 \x01(\x0b\x32\x10.ctl.iox.Display\x12)\n\x08valveMsg\x18\x02 \x01(\x0b\x32\x15.ctl.iox.ValveControlH\x00\x12\"\n\x08\x61\x62ortMsg\x18\x03 \x01(\x0b\x32\x0e.ctl.iox.AbortH\x00\x12,\n\ntest_state\x18\x04 \x01(\x0b\x32\x16.ctl.iox.DockTestStateH\x00\x42\x0c\n\ncontrolMsgb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_readings__pb2.DESCRIPTOR,ctl_dot_iox_dot_cal__record__pb2.DESCRIPTOR,])




_VALVECONTROL = _descriptor.Descriptor(
  name='ValveControl',
  full_name='ctl.iox.ValveControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='ctl.iox.ValveControl.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_time', full_name='ctl.iox.ValveControl.max_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=137,
)


_ABORT = _descriptor.Descriptor(
  name='Abort',
  full_name='ctl.iox.Abort',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=146,
)


_DISPLAY = _descriptor.Descriptor(
  name='Display',
  full_name='ctl.iox.Display',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='display_string', full_name='ctl.iox.Display.display_string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radix_point_is_comma', full_name='ctl.iox.Display.radix_point_is_comma', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=211,
)


_DOCKSENSORSTATE = _descriptor.Descriptor(
  name='DockSensorState',
  full_name='ctl.iox.DockSensorState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ctl.iox.DockSensorState.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reading', full_name='ctl.iox.DockSensorState.reading', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_result', full_name='ctl.iox.DockSensorState.test_result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_type', full_name='ctl.iox.DockSensorState.test_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_reading', full_name='ctl.iox.DockSensorState.target_reading', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=402,
)


_DOCKTESTSTATE = _descriptor.Descriptor(
  name='DockTestState',
  full_name='ctl.iox.DockTestState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor', full_name='ctl.iox.DockTestState.sensor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=461,
)


_DOCKCONTROL = _descriptor.Descriptor(
  name='DockControl',
  full_name='ctl.iox.DockControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='displayMsg', full_name='ctl.iox.DockControl.displayMsg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valveMsg', full_name='ctl.iox.DockControl.valveMsg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abortMsg', full_name='ctl.iox.DockControl.abortMsg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_state', full_name='ctl.iox.DockControl.test_state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='controlMsg', full_name='ctl.iox.DockControl.controlMsg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=464,
  serialized_end=654,
)

_DOCKSENSORSTATE.fields_by_name['reading'].message_type = ctl_dot_iox_dot_readings__pb2._READING
_DOCKSENSORSTATE.fields_by_name['test_result'].enum_type = ctl_dot_iox_dot_cal__record__pb2._TESTRESULT
_DOCKSENSORSTATE.fields_by_name['test_type'].enum_type = ctl_dot_iox_dot_cal__record__pb2._TESTTYPE
_DOCKSENSORSTATE.fields_by_name['target_reading'].message_type = ctl_dot_iox_dot_readings__pb2._READING
_DOCKTESTSTATE.fields_by_name['sensor'].message_type = _DOCKSENSORSTATE
_DOCKCONTROL.fields_by_name['displayMsg'].message_type = _DISPLAY
_DOCKCONTROL.fields_by_name['valveMsg'].message_type = _VALVECONTROL
_DOCKCONTROL.fields_by_name['abortMsg'].message_type = _ABORT
_DOCKCONTROL.fields_by_name['test_state'].message_type = _DOCKTESTSTATE
_DOCKCONTROL.oneofs_by_name['controlMsg'].fields.append(
  _DOCKCONTROL.fields_by_name['valveMsg'])
_DOCKCONTROL.fields_by_name['valveMsg'].containing_oneof = _DOCKCONTROL.oneofs_by_name['controlMsg']
_DOCKCONTROL.oneofs_by_name['controlMsg'].fields.append(
  _DOCKCONTROL.fields_by_name['abortMsg'])
_DOCKCONTROL.fields_by_name['abortMsg'].containing_oneof = _DOCKCONTROL.oneofs_by_name['controlMsg']
_DOCKCONTROL.oneofs_by_name['controlMsg'].fields.append(
  _DOCKCONTROL.fields_by_name['test_state'])
_DOCKCONTROL.fields_by_name['test_state'].containing_oneof = _DOCKCONTROL.oneofs_by_name['controlMsg']
DESCRIPTOR.message_types_by_name['ValveControl'] = _VALVECONTROL
DESCRIPTOR.message_types_by_name['Abort'] = _ABORT
DESCRIPTOR.message_types_by_name['Display'] = _DISPLAY
DESCRIPTOR.message_types_by_name['DockSensorState'] = _DOCKSENSORSTATE
DESCRIPTOR.message_types_by_name['DockTestState'] = _DOCKTESTSTATE
DESCRIPTOR.message_types_by_name['DockControl'] = _DOCKCONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValveControl = _reflection.GeneratedProtocolMessageType('ValveControl', (_message.Message,), {
  'DESCRIPTOR' : _VALVECONTROL,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.ValveControl)
  })
_sym_db.RegisterMessage(ValveControl)

Abort = _reflection.GeneratedProtocolMessageType('Abort', (_message.Message,), {
  'DESCRIPTOR' : _ABORT,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.Abort)
  })
_sym_db.RegisterMessage(Abort)

Display = _reflection.GeneratedProtocolMessageType('Display', (_message.Message,), {
  'DESCRIPTOR' : _DISPLAY,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.Display)
  })
_sym_db.RegisterMessage(Display)

DockSensorState = _reflection.GeneratedProtocolMessageType('DockSensorState', (_message.Message,), {
  'DESCRIPTOR' : _DOCKSENSORSTATE,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockSensorState)
  })
_sym_db.RegisterMessage(DockSensorState)

DockTestState = _reflection.GeneratedProtocolMessageType('DockTestState', (_message.Message,), {
  'DESCRIPTOR' : _DOCKTESTSTATE,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockTestState)
  })
_sym_db.RegisterMessage(DockTestState)

DockControl = _reflection.GeneratedProtocolMessageType('DockControl', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCONTROL,
  '__module__' : 'ctl.iox.dock_control_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockControl)
  })
_sym_db.RegisterMessage(DockControl)


# @@protoc_insertion_point(module_scope)
