# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_time.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_time.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x63tl/iox/dock_time.proto\x12\x07\x63tl.iox\"\x11\n\x0f\x44ockTimeRequest\"#\n\x10\x44ockTimeResponse\x12\x0f\n\x07utcTime\x18\x01 \x01(\x04\x62\x06proto3')
)




_DOCKTIMEREQUEST = _descriptor.Descriptor(
  name='DockTimeRequest',
  full_name='ctl.iox.DockTimeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=53,
)


_DOCKTIMERESPONSE = _descriptor.Descriptor(
  name='DockTimeResponse',
  full_name='ctl.iox.DockTimeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='utcTime', full_name='ctl.iox.DockTimeResponse.utcTime', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['DockTimeRequest'] = _DOCKTIMEREQUEST
DESCRIPTOR.message_types_by_name['DockTimeResponse'] = _DOCKTIMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockTimeRequest = _reflection.GeneratedProtocolMessageType('DockTimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKTIMEREQUEST,
  '__module__' : 'ctl.iox.dock_time_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockTimeRequest)
  })
_sym_db.RegisterMessage(DockTimeRequest)

DockTimeResponse = _reflection.GeneratedProtocolMessageType('DockTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKTIMERESPONSE,
  '__module__' : 'ctl.iox.dock_time_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockTimeResponse)
  })
_sym_db.RegisterMessage(DockTimeResponse)


# @@protoc_insertion_point(module_scope)
