# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_cylinder_configuration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import dock_shared_pb2 as ctl_dot_iox_dot_dock__shared__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_cylinder_configuration.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)ctl/iox/dock_cylinder_configuration.proto\x12\x07\x63tl.iox\x1a\x19\x63tl/iox/dock_shared.proto\"t\n DockCylinderConfigurationRequest\x12\x1e\n\x16\x63ylinder_holder_serial\x18\x01 \x01(\x07\x12\x30\n\x0f\x63ylinder_config\x18\x02 \x01(\x0b\x32\x17.ctl.iox.CylinderConfig\"u\n!DockCylinderConfigurationResponse\x12\x1e\n\x16\x63ylinder_holder_serial\x18\x01 \x01(\x07\x12\x30\n\x0f\x63ylinder_config\x18\x02 \x01(\x0b\x32\x17.ctl.iox.CylinderConfigb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_dock__shared__pb2.DESCRIPTOR,])




_DOCKCYLINDERCONFIGURATIONREQUEST = _descriptor.Descriptor(
  name='DockCylinderConfigurationRequest',
  full_name='ctl.iox.DockCylinderConfigurationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cylinder_holder_serial', full_name='ctl.iox.DockCylinderConfigurationRequest.cylinder_holder_serial', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinder_config', full_name='ctl.iox.DockCylinderConfigurationRequest.cylinder_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=197,
)


_DOCKCYLINDERCONFIGURATIONRESPONSE = _descriptor.Descriptor(
  name='DockCylinderConfigurationResponse',
  full_name='ctl.iox.DockCylinderConfigurationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cylinder_holder_serial', full_name='ctl.iox.DockCylinderConfigurationResponse.cylinder_holder_serial', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cylinder_config', full_name='ctl.iox.DockCylinderConfigurationResponse.cylinder_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=316,
)

_DOCKCYLINDERCONFIGURATIONREQUEST.fields_by_name['cylinder_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._CYLINDERCONFIG
_DOCKCYLINDERCONFIGURATIONRESPONSE.fields_by_name['cylinder_config'].message_type = ctl_dot_iox_dot_dock__shared__pb2._CYLINDERCONFIG
DESCRIPTOR.message_types_by_name['DockCylinderConfigurationRequest'] = _DOCKCYLINDERCONFIGURATIONREQUEST
DESCRIPTOR.message_types_by_name['DockCylinderConfigurationResponse'] = _DOCKCYLINDERCONFIGURATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockCylinderConfigurationRequest = _reflection.GeneratedProtocolMessageType('DockCylinderConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCYLINDERCONFIGURATIONREQUEST,
  '__module__' : 'ctl.iox.dock_cylinder_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockCylinderConfigurationRequest)
  })
_sym_db.RegisterMessage(DockCylinderConfigurationRequest)

DockCylinderConfigurationResponse = _reflection.GeneratedProtocolMessageType('DockCylinderConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOCKCYLINDERCONFIGURATIONRESPONSE,
  '__module__' : 'ctl.iox.dock_cylinder_configuration_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockCylinderConfigurationResponse)
  })
_sym_db.RegisterMessage(DockCylinderConfigurationResponse)


# @@protoc_insertion_point(module_scope)
