# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/dock_authentication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/dock_authentication.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!ctl/iox/dock_authentication.proto\x12\x07\x63tl.iox\"-\n\x19\x44ockAuthenticationRequest\x12\x10\n\x08passcode\x18\x01 \x01(\tb\x06proto3')
)




_DOCKAUTHENTICATIONREQUEST = _descriptor.Descriptor(
  name='DockAuthenticationRequest',
  full_name='ctl.iox.DockAuthenticationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='passcode', full_name='ctl.iox.DockAuthenticationRequest.passcode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['DockAuthenticationRequest'] = _DOCKAUTHENTICATIONREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DockAuthenticationRequest = _reflection.GeneratedProtocolMessageType('DockAuthenticationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOCKAUTHENTICATIONREQUEST,
  '__module__' : 'ctl.iox.dock_authentication_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockAuthenticationRequest)
  })
_sym_db.RegisterMessage(DockAuthenticationRequest)


# @@protoc_insertion_point(module_scope)
