# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/error.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63tl/iox/error.proto\x12\x07\x63tl.iox\"B\n\rErrorResponse\x12 \n\x04\x63ode\x18\x01 \x01(\x0e\x32\x12.ctl.iox.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t*\x93\x02\n\tErrorCode\x12\x15\n\x11\x45RROR_UNSPECIFIED\x10\x00\x12\x19\n\x15\x45RROR_UNKNOWN_MESSAGE\x10\x01\x12\x18\n\x14\x45RROR_INVALID_CONFIG\x10\x02\x12\x1b\n\x17\x45RROR_INVALID_SUBSYSTEM\x10\x03\x12\x1b\n\x17\x45RROR_NOT_AUTHENTICATED\x10\x04\x12\x1e\n\x1a\x45RROR_WRONG_AUTHENTICATION\x10\x05\x12\x19\n\x15\x45RROR_INVALID_REQUEST\x10\x06\x12\x13\n\x0f\x45RROR_BAD_STATE\x10\x07\x12\x12\n\x0e\x45RROR_TOO_MANY\x10\x08\x12\x1c\n\x18\x45RROR_NO_SUCH_REQUEST_ID\x10\tb\x06proto3')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='ctl.iox.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_UNKNOWN_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_SUBSYSTEM', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NOT_AUTHENTICATED', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_WRONG_AUTHENTICATION', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_REQUEST', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_BAD_STATE', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_TOO_MANY', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_NO_SUCH_REQUEST_ID', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=101,
  serialized_end=376,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
ERROR_UNSPECIFIED = 0
ERROR_UNKNOWN_MESSAGE = 1
ERROR_INVALID_CONFIG = 2
ERROR_INVALID_SUBSYSTEM = 3
ERROR_NOT_AUTHENTICATED = 4
ERROR_WRONG_AUTHENTICATION = 5
ERROR_INVALID_REQUEST = 6
ERROR_BAD_STATE = 7
ERROR_TOO_MANY = 8
ERROR_NO_SUCH_REQUEST_ID = 9



_ERRORRESPONSE = _descriptor.Descriptor(
  name='ErrorResponse',
  full_name='ctl.iox.ErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='ctl.iox.ErrorResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='ctl.iox.ErrorResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=98,
)

_ERRORRESPONSE.fields_by_name['code'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['ErrorResponse'] = _ERRORRESPONSE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'ctl.iox.error_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)


# @@protoc_insertion_point(module_scope)
