# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/inst_profile_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import pf_instrument_config_pb2 as ctl_dot_iox_dot_pf__instrument__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/inst_profile_data.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1f\x63tl/iox/inst_profile_data.proto\x12\x07\x63tl.iox\x1a\"ctl/iox/pf_instrument_config.proto\"\x1e\n\x1cInstrumentProfileDataRequest\"J\n\x1dInstrumentProfileDataResponse\x12)\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x19.ctl.iox.InstrumentConfigb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_pf__instrument__config__pb2.DESCRIPTOR,])




_INSTRUMENTPROFILEDATAREQUEST = _descriptor.Descriptor(
  name='InstrumentProfileDataRequest',
  full_name='ctl.iox.InstrumentProfileDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=110,
)


_INSTRUMENTPROFILEDATARESPONSE = _descriptor.Descriptor(
  name='InstrumentProfileDataResponse',
  full_name='ctl.iox.InstrumentProfileDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='config', full_name='ctl.iox.InstrumentProfileDataResponse.config', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=186,
)

_INSTRUMENTPROFILEDATARESPONSE.fields_by_name['config'].message_type = ctl_dot_iox_dot_pf__instrument__config__pb2._INSTRUMENTCONFIG
DESCRIPTOR.message_types_by_name['InstrumentProfileDataRequest'] = _INSTRUMENTPROFILEDATAREQUEST
DESCRIPTOR.message_types_by_name['InstrumentProfileDataResponse'] = _INSTRUMENTPROFILEDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentProfileDataRequest = _reflection.GeneratedProtocolMessageType('InstrumentProfileDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTPROFILEDATAREQUEST,
  '__module__' : 'ctl.iox.inst_profile_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.InstrumentProfileDataRequest)
  })
_sym_db.RegisterMessage(InstrumentProfileDataRequest)

InstrumentProfileDataResponse = _reflection.GeneratedProtocolMessageType('InstrumentProfileDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTPROFILEDATARESPONSE,
  '__module__' : 'ctl.iox.inst_profile_data_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.InstrumentProfileDataResponse)
  })
_sym_db.RegisterMessage(InstrumentProfileDataResponse)


# @@protoc_insertion_point(module_scope)
