# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/inst_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import connectivity_pb2 as ctl_dot_iox_dot_connectivity__pb2
from ctl.iox import inst_record_pb2 as ctl_dot_iox_dot_inst__record__pb2
from ctl.iox import pf_instrument_config_pb2 as ctl_dot_iox_dot_pf__instrument__config__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/inst_wrapper.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1a\x63tl/iox/inst_wrapper.proto\x12\x07\x63tl.iox\x1a\x1a\x63tl/iox/connectivity.proto\x1a\x19\x63tl/iox/inst_record.proto\x1a\"ctl/iox/pf_instrument_config.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n\x11InstrumentWrapper\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x63onnectivity_msg\x18\x03 \x01(\x0b\x32\x18.ctl.iox.ConnectivityMsgH\x00\x12*\n\x0binst_record\x18\x04 \x01(\x0b\x32\x13.ctl.iox.InstRecordH\x00\x12\x30\n\x0binst_config\x18\x05 \x01(\x0b\x32\x19.ctl.iox.InstrumentConfigH\x00\x12\x16\n\x0elatest_session\x18\n \x01(\r\x12\x14\n\x0clatest_event\x18\x0b \x01(\r\x12,\n\x0f\x62\x61tched_records\x18\x0c \x03(\x0b\x32\x13.ctl.iox.InstRecord\x12\x0c\n\x04hash\x18\r \x01(\x0c\x42\x06\n\x04\x64\x61tab\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_connectivity__pb2.DESCRIPTOR,ctl_dot_iox_dot_inst__record__pb2.DESCRIPTOR,ctl_dot_iox_dot_pf__instrument__config__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_INSTRUMENTWRAPPER = _descriptor.Descriptor(
  name='InstrumentWrapper',
  full_name='ctl.iox.InstrumentWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.InstrumentWrapper.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ctl.iox.InstrumentWrapper.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connectivity_msg', full_name='ctl.iox.InstrumentWrapper.connectivity_msg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_record', full_name='ctl.iox.InstrumentWrapper.inst_record', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inst_config', full_name='ctl.iox.InstrumentWrapper.inst_config', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_session', full_name='ctl.iox.InstrumentWrapper.latest_session', index=5,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_event', full_name='ctl.iox.InstrumentWrapper.latest_event', index=6,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batched_records', full_name='ctl.iox.InstrumentWrapper.batched_records', index=7,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='ctl.iox.InstrumentWrapper.hash', index=8,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='ctl.iox.InstrumentWrapper.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=164,
  serialized_end=505,
)

_INSTRUMENTWRAPPER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_INSTRUMENTWRAPPER.fields_by_name['connectivity_msg'].message_type = ctl_dot_iox_dot_connectivity__pb2._CONNECTIVITYMSG
_INSTRUMENTWRAPPER.fields_by_name['inst_record'].message_type = ctl_dot_iox_dot_inst__record__pb2._INSTRECORD
_INSTRUMENTWRAPPER.fields_by_name['inst_config'].message_type = ctl_dot_iox_dot_pf__instrument__config__pb2._INSTRUMENTCONFIG
_INSTRUMENTWRAPPER.fields_by_name['batched_records'].message_type = ctl_dot_iox_dot_inst__record__pb2._INSTRECORD
_INSTRUMENTWRAPPER.oneofs_by_name['data'].fields.append(
  _INSTRUMENTWRAPPER.fields_by_name['connectivity_msg'])
_INSTRUMENTWRAPPER.fields_by_name['connectivity_msg'].containing_oneof = _INSTRUMENTWRAPPER.oneofs_by_name['data']
_INSTRUMENTWRAPPER.oneofs_by_name['data'].fields.append(
  _INSTRUMENTWRAPPER.fields_by_name['inst_record'])
_INSTRUMENTWRAPPER.fields_by_name['inst_record'].containing_oneof = _INSTRUMENTWRAPPER.oneofs_by_name['data']
_INSTRUMENTWRAPPER.oneofs_by_name['data'].fields.append(
  _INSTRUMENTWRAPPER.fields_by_name['inst_config'])
_INSTRUMENTWRAPPER.fields_by_name['inst_config'].containing_oneof = _INSTRUMENTWRAPPER.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['InstrumentWrapper'] = _INSTRUMENTWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentWrapper = _reflection.GeneratedProtocolMessageType('InstrumentWrapper', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTWRAPPER,
  '__module__' : 'ctl.iox.inst_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.InstrumentWrapper)
  })
_sym_db.RegisterMessage(InstrumentWrapper)


# @@protoc_insertion_point(module_scope)
