# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/inst_cloud_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/inst_cloud_response.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!ctl/iox/inst_cloud_response.proto\x12\x07\x63tl.iox\"M\n\rCloudResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\r\x12\x13\n\x0bresult_code\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tb\x06proto3')
)




_CLOUDRESPONSE = _descriptor.Descriptor(
  name='CloudResponse',
  full_name='ctl.iox.CloudResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_id', full_name='ctl.iox.CloudResponse.request_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_code', full_name='ctl.iox.CloudResponse.result_code', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='ctl.iox.CloudResponse.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['CloudResponse'] = _CLOUDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloudResponse = _reflection.GeneratedProtocolMessageType('CloudResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOUDRESPONSE,
  '__module__' : 'ctl.iox.inst_cloud_response_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.CloudResponse)
  })
_sym_db.RegisterMessage(CloudResponse)


# @@protoc_insertion_point(module_scope)
