# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/inst_debug.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import inst_mode_pb2 as ctl_dot_iox_dot_inst__mode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/inst_debug.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x63tl/iox/inst_debug.proto\x12\x07\x63tl.iox\x1a\x17\x63tl/iox/inst_mode.proto\"L\n\x0b\x44\x65\x62ugRecord\x12\x0f\n\x07message\x18\x01 \x01(\t\x12,\n\rspecial_state\x18\x02 \x01(\x0e\x32\x15.ctl.iox.SpecialStateb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_inst__mode__pb2.DESCRIPTOR,])




_DEBUGRECORD = _descriptor.Descriptor(
  name='DebugRecord',
  full_name='ctl.iox.DebugRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ctl.iox.DebugRecord.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='special_state', full_name='ctl.iox.DebugRecord.special_state', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=138,
)

_DEBUGRECORD.fields_by_name['special_state'].enum_type = ctl_dot_iox_dot_inst__mode__pb2._SPECIALSTATE
DESCRIPTOR.message_types_by_name['DebugRecord'] = _DEBUGRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DebugRecord = _reflection.GeneratedProtocolMessageType('DebugRecord', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGRECORD,
  '__module__' : 'ctl.iox.inst_debug_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DebugRecord)
  })
_sym_db.RegisterMessage(DebugRecord)


# @@protoc_insertion_point(module_scope)
