# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/location.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/location.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63tl/iox/location.proto\x12\x07\x63tl.iox\"\x8c\x01\n\x0eLocationRecord\x12\x11\n\tlongitude\x18\x01 \x01(\x0f\x12\x10\n\x08latitude\x18\x02 \x01(\x0f\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\r\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x01(\r\x12\x0c\n\x04hdop\x18\x05 \x01(\r\x12\x0c\n\x04sats\x18\x06 \x01(\r\x12\x15\n\repoch_seconds\x18\x07 \x01(\rb\x06proto3')
)




_LOCATIONRECORD = _descriptor.Descriptor(
  name='LocationRecord',
  full_name='ctl.iox.LocationRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='ctl.iox.LocationRecord.longitude', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='ctl.iox.LocationRecord.latitude', index=1,
      number=2, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='ctl.iox.LocationRecord.altitude', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='ctl.iox.LocationRecord.accuracy', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hdop', full_name='ctl.iox.LocationRecord.hdop', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sats', full_name='ctl.iox.LocationRecord.sats', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_seconds', full_name='ctl.iox.LocationRecord.epoch_seconds', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=176,
)

DESCRIPTOR.message_types_by_name['LocationRecord'] = _LOCATIONRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocationRecord = _reflection.GeneratedProtocolMessageType('LocationRecord', (_message.Message,), {
  'DESCRIPTOR' : _LOCATIONRECORD,
  '__module__' : 'ctl.iox.location_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.LocationRecord)
  })
_sym_db.RegisterMessage(LocationRecord)


# @@protoc_insertion_point(module_scope)
