# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/readings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import common_pb2 as ctl_dot_iox_dot_common__pb2
from ctl.iox import pf_sensor_config_pb2 as ctl_dot_iox_dot_pf__sensor__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/readings.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x63tl/iox/readings.proto\x12\x07\x63tl.iox\x1a\x14\x63tl/iox/common.proto\x1a\x1e\x63tl/iox/pf_sensor_config.proto\"\xf5\x01\n\x07Reading\x12\x0f\n\x07reading\x18\x01 \x01(\x11\x12\"\n\x08gas_type\x18\x02 \x01(\x0e\x32\x10.ctl.iox.GasType\x12\'\n\nresolution\x18\x03 \x01(\x0e\x32\x13.ctl.iox.Resolution\x12\x1b\n\x04unit\x18\x04 \x01(\x0e\x32\r.ctl.iox.Unit\x12\x13\n\x0btemperature\x18\x05 \x01(\x11\x12/\n\x0bsensor_type\x18\x06 \x01(\x0e\x32\x1a.ctl.iox.SensorCfgGastypes\x12\x16\n\x0escaling_factor\x18\x07 \x01(\x02\x12\x11\n\tunit_name\x18\x08 \x01(\t\"m\n\x0eReadingsRecord\x12\"\n\x08readings\x18\x01 \x03(\x0b\x32\x10.ctl.iox.Reading\x12\x10\n\x08humidity\x18\x02 \x01(\x11\x12\x10\n\x08pressure\x18\x03 \x01(\x11\x12\x13\n\x0btemperature\x18\x04 \x01(\x11\"Y\n\nAdcReading\x12!\n\x07reading\x18\x01 \x01(\x0b\x32\x10.ctl.iox.Reading\x12\r\n\x05\x63ount\x18\x02 \x01(\x11\x12\x19\n\x11\x63ompensated_count\x18\x03 \x01(\x11\"<\n\x13\x41\x64\x63ReadingsResponse\x12%\n\x08readings\x18\x01 \x03(\x0b\x32\x13.ctl.iox.AdcReading\"\x14\n\x12\x41\x64\x63ReadingsRequestb\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_common__pb2.DESCRIPTOR,ctl_dot_iox_dot_pf__sensor__config__pb2.DESCRIPTOR,])




_READING = _descriptor.Descriptor(
  name='Reading',
  full_name='ctl.iox.Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading', full_name='ctl.iox.Reading.reading', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_type', full_name='ctl.iox.Reading.gas_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resolution', full_name='ctl.iox.Reading.resolution', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='ctl.iox.Reading.unit', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='ctl.iox.Reading.temperature', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_type', full_name='ctl.iox.Reading.sensor_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaling_factor', full_name='ctl.iox.Reading.scaling_factor', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_name', full_name='ctl.iox.Reading.unit_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=335,
)


_READINGSRECORD = _descriptor.Descriptor(
  name='ReadingsRecord',
  full_name='ctl.iox.ReadingsRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readings', full_name='ctl.iox.ReadingsRecord.readings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='ctl.iox.ReadingsRecord.humidity', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='ctl.iox.ReadingsRecord.pressure', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='ctl.iox.ReadingsRecord.temperature', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=446,
)


_ADCREADING = _descriptor.Descriptor(
  name='AdcReading',
  full_name='ctl.iox.AdcReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading', full_name='ctl.iox.AdcReading.reading', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='ctl.iox.AdcReading.count', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compensated_count', full_name='ctl.iox.AdcReading.compensated_count', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=537,
)


_ADCREADINGSRESPONSE = _descriptor.Descriptor(
  name='AdcReadingsResponse',
  full_name='ctl.iox.AdcReadingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='readings', full_name='ctl.iox.AdcReadingsResponse.readings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=599,
)


_ADCREADINGSREQUEST = _descriptor.Descriptor(
  name='AdcReadingsRequest',
  full_name='ctl.iox.AdcReadingsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=621,
)

_READING.fields_by_name['gas_type'].enum_type = ctl_dot_iox_dot_common__pb2._GASTYPE
_READING.fields_by_name['resolution'].enum_type = ctl_dot_iox_dot_common__pb2._RESOLUTION
_READING.fields_by_name['unit'].enum_type = ctl_dot_iox_dot_common__pb2._UNIT
_READING.fields_by_name['sensor_type'].enum_type = ctl_dot_iox_dot_pf__sensor__config__pb2._SENSORCFGGASTYPES
_READINGSRECORD.fields_by_name['readings'].message_type = _READING
_ADCREADING.fields_by_name['reading'].message_type = _READING
_ADCREADINGSRESPONSE.fields_by_name['readings'].message_type = _ADCREADING
DESCRIPTOR.message_types_by_name['Reading'] = _READING
DESCRIPTOR.message_types_by_name['ReadingsRecord'] = _READINGSRECORD
DESCRIPTOR.message_types_by_name['AdcReading'] = _ADCREADING
DESCRIPTOR.message_types_by_name['AdcReadingsResponse'] = _ADCREADINGSRESPONSE
DESCRIPTOR.message_types_by_name['AdcReadingsRequest'] = _ADCREADINGSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reading = _reflection.GeneratedProtocolMessageType('Reading', (_message.Message,), {
  'DESCRIPTOR' : _READING,
  '__module__' : 'ctl.iox.readings_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.Reading)
  })
_sym_db.RegisterMessage(Reading)

ReadingsRecord = _reflection.GeneratedProtocolMessageType('ReadingsRecord', (_message.Message,), {
  'DESCRIPTOR' : _READINGSRECORD,
  '__module__' : 'ctl.iox.readings_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.ReadingsRecord)
  })
_sym_db.RegisterMessage(ReadingsRecord)

AdcReading = _reflection.GeneratedProtocolMessageType('AdcReading', (_message.Message,), {
  'DESCRIPTOR' : _ADCREADING,
  '__module__' : 'ctl.iox.readings_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.AdcReading)
  })
_sym_db.RegisterMessage(AdcReading)

AdcReadingsResponse = _reflection.GeneratedProtocolMessageType('AdcReadingsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADCREADINGSRESPONSE,
  '__module__' : 'ctl.iox.readings_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.AdcReadingsResponse)
  })
_sym_db.RegisterMessage(AdcReadingsResponse)

AdcReadingsRequest = _reflection.GeneratedProtocolMessageType('AdcReadingsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADCREADINGSREQUEST,
  '__module__' : 'ctl.iox.readings_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.AdcReadingsRequest)
  })
_sym_db.RegisterMessage(AdcReadingsRequest)


# @@protoc_insertion_point(module_scope)
