# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/sensor_states_record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ctl.iox import pf_sensor_config_pb2 as ctl_dot_iox_dot_pf__sensor__config__pb2
from ctl.iox import cal_record_pb2 as ctl_dot_iox_dot_cal__record__pb2
from ctl.iox import X1Status_pb2 as ctl_dot_iox_dot_X1Status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/sensor_states_record.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"ctl/iox/sensor_states_record.proto\x12\x07\x63tl.iox\x1a\x1e\x63tl/iox/pf_sensor_config.proto\x1a\x18\x63tl/iox/cal_record.proto\x1a\x16\x63tl/iox/X1Status.proto\"@\n\x12SensorStatesRecord\x12*\n\x0csensor_state\x18\x01 \x03(\x0b\x32\x14.ctl.iox.SensorState\"\xc2\x02\n\x0bSensorState\x12\x15\n\rsensor_serial\x18\x01 \x01(\t\x12,\n\x08gas_type\x18\x02 \x01(\x0e\x32\x1a.ctl.iox.SensorCfgGastypes\x12\x43\n\x06health\x18\x03 \x01(\x0e\x32\x33.ctl.iox.X1SensorStatus.SensorStat_LifeHealthStates\x12\x10\n\x08\x63\x61l_date\x18\x04 \x01(\x04\x12\'\n\ncal_result\x18\x05 \x01(\x0e\x32\x13.ctl.iox.TestResult\x12\x11\n\tbump_date\x18\x06 \x01(\x04\x12(\n\x0b\x62ump_result\x18\x07 \x01(\x0e\x32\x13.ctl.iox.TestResult\x12\x17\n\x0f\x63\x61l_expire_date\x18\x08 \x01(\x04\x12\x18\n\x10\x62ump_expire_date\x18\t \x01(\x04\x62\x06proto3')
  ,
  dependencies=[ctl_dot_iox_dot_pf__sensor__config__pb2.DESCRIPTOR,ctl_dot_iox_dot_cal__record__pb2.DESCRIPTOR,ctl_dot_iox_dot_X1Status__pb2.DESCRIPTOR,])




_SENSORSTATESRECORD = _descriptor.Descriptor(
  name='SensorStatesRecord',
  full_name='ctl.iox.SensorStatesRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_state', full_name='ctl.iox.SensorStatesRecord.sensor_state', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=193,
)


_SENSORSTATE = _descriptor.Descriptor(
  name='SensorState',
  full_name='ctl.iox.SensorState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_serial', full_name='ctl.iox.SensorState.sensor_serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas_type', full_name='ctl.iox.SensorState.gas_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health', full_name='ctl.iox.SensorState.health', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cal_date', full_name='ctl.iox.SensorState.cal_date', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cal_result', full_name='ctl.iox.SensorState.cal_result', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bump_date', full_name='ctl.iox.SensorState.bump_date', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bump_result', full_name='ctl.iox.SensorState.bump_result', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cal_expire_date', full_name='ctl.iox.SensorState.cal_expire_date', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bump_expire_date', full_name='ctl.iox.SensorState.bump_expire_date', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=518,
)

_SENSORSTATESRECORD.fields_by_name['sensor_state'].message_type = _SENSORSTATE
_SENSORSTATE.fields_by_name['gas_type'].enum_type = ctl_dot_iox_dot_pf__sensor__config__pb2._SENSORCFGGASTYPES
_SENSORSTATE.fields_by_name['health'].enum_type = ctl_dot_iox_dot_X1Status__pb2._X1SENSORSTATUS_SENSORSTAT_LIFEHEALTHSTATES
_SENSORSTATE.fields_by_name['cal_result'].enum_type = ctl_dot_iox_dot_cal__record__pb2._TESTRESULT
_SENSORSTATE.fields_by_name['bump_result'].enum_type = ctl_dot_iox_dot_cal__record__pb2._TESTRESULT
DESCRIPTOR.message_types_by_name['SensorStatesRecord'] = _SENSORSTATESRECORD
DESCRIPTOR.message_types_by_name['SensorState'] = _SENSORSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorStatesRecord = _reflection.GeneratedProtocolMessageType('SensorStatesRecord', (_message.Message,), {
  'DESCRIPTOR' : _SENSORSTATESRECORD,
  '__module__' : 'ctl.iox.sensor_states_record_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.SensorStatesRecord)
  })
_sym_db.RegisterMessage(SensorStatesRecord)

SensorState = _reflection.GeneratedProtocolMessageType('SensorState', (_message.Message,), {
  'DESCRIPTOR' : _SENSORSTATE,
  '__module__' : 'ctl.iox.sensor_states_record_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.SensorState)
  })
_sym_db.RegisterMessage(SensorState)


# @@protoc_insertion_point(module_scope)
