# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/tag.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63tl/iox/tag.proto\x12\x07\x63tl.iox\"J\n\x11InstrumentPayload\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12\x0f\n\x07\x62le_mac\x18\x02 \x01(\x0c\x12\x17\n\x0f\x61\x63tivation_code\x18\x03 \x01(\x0c\"\x1d\n\x0e\x42\x61tteryPayload\x12\x0b\n\x03gsn\x18\x01 \x01(\x0c\"Y\n\x0b\x44ockPayload\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12\x0f\n\x07\x62le_mac\x18\x02 \x01(\x0c\x12\x13\n\x0b\x63\x61libration\x18\x03 \x01(\x08\x12\x17\n\x0f\x61\x63tivation_code\x18\x04 \x01(\x0c\"?\n\nMucPayload\x12\x0b\n\x03ssn\x18\x01 \x01(\x0c\x12\x0b\n\x03\x62\x61y\x18\x02 \x01(\r\x12\x17\n\x0f\x61\x63tivation_code\x18\x03 \x01(\x0c\"\x11\n\x0fSafezonePayload\"4\n\x16\x45nterProductionPayload\x12\x1a\n\x12production_tag_key\x18\x01 \x01(\x0c\"\xb5\x02\n\x05IoTag\x12\x0b\n\x03uid\x18\x01 \x01(\x0c\x12\x30\n\ninstrument\x18\x02 \x01(\x0b\x32\x1a.ctl.iox.InstrumentPayloadH\x00\x12$\n\x04\x64ock\x18\x05 \x01(\x0b\x32\x14.ctl.iox.DockPayloadH\x00\x12\"\n\x03muc\x18\x06 \x01(\x0b\x32\x13.ctl.iox.MucPayloadH\x00\x12,\n\x08safezone\x18\x07 \x01(\x0b\x32\x18.ctl.iox.SafezonePayloadH\x00\x12\x35\n\nproduction\x18\x08 \x01(\x0b\x32\x1f.ctl.iox.EnterProductionPayloadH\x00\x12*\n\x07\x62\x61ttery\x18\t \x01(\x0b\x32\x17.ctl.iox.BatteryPayloadH\x00\x42\x06\n\x04\x64\x61taJ\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\x62\x06proto3')
)




_INSTRUMENTPAYLOAD = _descriptor.Descriptor(
  name='InstrumentPayload',
  full_name='ctl.iox.InstrumentPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.InstrumentPayload.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ble_mac', full_name='ctl.iox.InstrumentPayload.ble_mac', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_code', full_name='ctl.iox.InstrumentPayload.activation_code', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=104,
)


_BATTERYPAYLOAD = _descriptor.Descriptor(
  name='BatteryPayload',
  full_name='ctl.iox.BatteryPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gsn', full_name='ctl.iox.BatteryPayload.gsn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=135,
)


_DOCKPAYLOAD = _descriptor.Descriptor(
  name='DockPayload',
  full_name='ctl.iox.DockPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.DockPayload.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ble_mac', full_name='ctl.iox.DockPayload.ble_mac', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calibration', full_name='ctl.iox.DockPayload.calibration', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_code', full_name='ctl.iox.DockPayload.activation_code', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=226,
)


_MUCPAYLOAD = _descriptor.Descriptor(
  name='MucPayload',
  full_name='ctl.iox.MucPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ssn', full_name='ctl.iox.MucPayload.ssn', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bay', full_name='ctl.iox.MucPayload.bay', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activation_code', full_name='ctl.iox.MucPayload.activation_code', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=291,
)


_SAFEZONEPAYLOAD = _descriptor.Descriptor(
  name='SafezonePayload',
  full_name='ctl.iox.SafezonePayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=310,
)


_ENTERPRODUCTIONPAYLOAD = _descriptor.Descriptor(
  name='EnterProductionPayload',
  full_name='ctl.iox.EnterProductionPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='production_tag_key', full_name='ctl.iox.EnterProductionPayload.production_tag_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=364,
)


_IOTAG = _descriptor.Descriptor(
  name='IoTag',
  full_name='ctl.iox.IoTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='ctl.iox.IoTag.uid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instrument', full_name='ctl.iox.IoTag.instrument', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dock', full_name='ctl.iox.IoTag.dock', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='muc', full_name='ctl.iox.IoTag.muc', index=3,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='safezone', full_name='ctl.iox.IoTag.safezone', index=4,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='production', full_name='ctl.iox.IoTag.production', index=5,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='ctl.iox.IoTag.battery', index=6,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='ctl.iox.IoTag.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=367,
  serialized_end=676,
)

_IOTAG.fields_by_name['instrument'].message_type = _INSTRUMENTPAYLOAD
_IOTAG.fields_by_name['dock'].message_type = _DOCKPAYLOAD
_IOTAG.fields_by_name['muc'].message_type = _MUCPAYLOAD
_IOTAG.fields_by_name['safezone'].message_type = _SAFEZONEPAYLOAD
_IOTAG.fields_by_name['production'].message_type = _ENTERPRODUCTIONPAYLOAD
_IOTAG.fields_by_name['battery'].message_type = _BATTERYPAYLOAD
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['instrument'])
_IOTAG.fields_by_name['instrument'].containing_oneof = _IOTAG.oneofs_by_name['data']
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['dock'])
_IOTAG.fields_by_name['dock'].containing_oneof = _IOTAG.oneofs_by_name['data']
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['muc'])
_IOTAG.fields_by_name['muc'].containing_oneof = _IOTAG.oneofs_by_name['data']
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['safezone'])
_IOTAG.fields_by_name['safezone'].containing_oneof = _IOTAG.oneofs_by_name['data']
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['production'])
_IOTAG.fields_by_name['production'].containing_oneof = _IOTAG.oneofs_by_name['data']
_IOTAG.oneofs_by_name['data'].fields.append(
  _IOTAG.fields_by_name['battery'])
_IOTAG.fields_by_name['battery'].containing_oneof = _IOTAG.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['InstrumentPayload'] = _INSTRUMENTPAYLOAD
DESCRIPTOR.message_types_by_name['BatteryPayload'] = _BATTERYPAYLOAD
DESCRIPTOR.message_types_by_name['DockPayload'] = _DOCKPAYLOAD
DESCRIPTOR.message_types_by_name['MucPayload'] = _MUCPAYLOAD
DESCRIPTOR.message_types_by_name['SafezonePayload'] = _SAFEZONEPAYLOAD
DESCRIPTOR.message_types_by_name['EnterProductionPayload'] = _ENTERPRODUCTIONPAYLOAD
DESCRIPTOR.message_types_by_name['IoTag'] = _IOTAG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstrumentPayload = _reflection.GeneratedProtocolMessageType('InstrumentPayload', (_message.Message,), {
  'DESCRIPTOR' : _INSTRUMENTPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.InstrumentPayload)
  })
_sym_db.RegisterMessage(InstrumentPayload)

BatteryPayload = _reflection.GeneratedProtocolMessageType('BatteryPayload', (_message.Message,), {
  'DESCRIPTOR' : _BATTERYPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.BatteryPayload)
  })
_sym_db.RegisterMessage(BatteryPayload)

DockPayload = _reflection.GeneratedProtocolMessageType('DockPayload', (_message.Message,), {
  'DESCRIPTOR' : _DOCKPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.DockPayload)
  })
_sym_db.RegisterMessage(DockPayload)

MucPayload = _reflection.GeneratedProtocolMessageType('MucPayload', (_message.Message,), {
  'DESCRIPTOR' : _MUCPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.MucPayload)
  })
_sym_db.RegisterMessage(MucPayload)

SafezonePayload = _reflection.GeneratedProtocolMessageType('SafezonePayload', (_message.Message,), {
  'DESCRIPTOR' : _SAFEZONEPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.SafezonePayload)
  })
_sym_db.RegisterMessage(SafezonePayload)

EnterProductionPayload = _reflection.GeneratedProtocolMessageType('EnterProductionPayload', (_message.Message,), {
  'DESCRIPTOR' : _ENTERPRODUCTIONPAYLOAD,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.EnterProductionPayload)
  })
_sym_db.RegisterMessage(EnterProductionPayload)

IoTag = _reflection.GeneratedProtocolMessageType('IoTag', (_message.Message,), {
  'DESCRIPTOR' : _IOTAG,
  '__module__' : 'ctl.iox.tag_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.IoTag)
  })
_sym_db.RegisterMessage(IoTag)


# @@protoc_insertion_point(module_scope)
