# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctl/iox/X1Datalog.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctl/iox/X1Datalog.proto',
  package='ctl.iox',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x63tl/iox/X1Datalog.proto\x12\x07\x63tl.iox\"?\n\tX1Datalog\"2\n\x0b\x44\x61talogType\x12\x0c\n\x08PERIODIC\x10\x00\x12\t\n\x05\x45VENT\x10\x01\x12\n\n\x06\x43ONFIG\x10\x02\x62\x06proto3')
)



_X1DATALOG_DATALOGTYPE = _descriptor.EnumDescriptor(
  name='DatalogType',
  full_name='ctl.iox.X1Datalog.DatalogType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PERIODIC', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=49,
  serialized_end=99,
)
_sym_db.RegisterEnumDescriptor(_X1DATALOG_DATALOGTYPE)


_X1DATALOG = _descriptor.Descriptor(
  name='X1Datalog',
  full_name='ctl.iox.X1Datalog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _X1DATALOG_DATALOGTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=99,
)

_X1DATALOG_DATALOGTYPE.containing_type = _X1DATALOG
DESCRIPTOR.message_types_by_name['X1Datalog'] = _X1DATALOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

X1Datalog = _reflection.GeneratedProtocolMessageType('X1Datalog', (_message.Message,), {
  'DESCRIPTOR' : _X1DATALOG,
  '__module__' : 'ctl.iox.X1Datalog_pb2'
  # @@protoc_insertion_point(class_scope:ctl.iox.X1Datalog)
  })
_sym_db.RegisterMessage(X1Datalog)


# @@protoc_insertion_point(module_scope)
